// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcg97I18tqlFUt97s67ODCZH2oyqYP_Fg',
    appId: '1:912217817262:web:ecaa7e7410a87395acad3f',
    messagingSenderId: '912217817262',
    projectId: 'nex-spot-app',
    authDomain: 'nex-spot-app.firebaseapp.com',
    storageBucket: 'nex-spot-app.appspot.com',
    measurementId: 'G-FGP4J4BC0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7vVwh2ePFxBv3j7M2L8REoL-bsq5yoT8',
    appId: '1:912217817262:android:bbe2ea1442b82a75acad3f',
    messagingSenderId: '912217817262',
    projectId: 'nex-spot-app',
    storageBucket: 'nex-spot-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuvTVnjWUPz0xd2cn9OE1XThloUUbMJkE',
    appId: '1:912217817262:ios:5b097f0321bc1af1acad3f',
    messagingSenderId: '912217817262',
    projectId: 'nex-spot-app',
    storageBucket: 'nex-spot-app.appspot.com',
    iosBundleId: 'com.example.nexSpotApp',
  );

}